USE [master]
GO
/****** Object:  Database [feedback]    Script Date: 12/27/2020 2:49:12 PM ******/
CREATE DATABASE [feedback]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'feedback', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\feedback.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'feedback_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\feedback_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [feedback] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [feedback].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [feedback] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [feedback] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [feedback] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [feedback] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [feedback] SET ARITHABORT OFF 
GO
ALTER DATABASE [feedback] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [feedback] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [feedback] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [feedback] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [feedback] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [feedback] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [feedback] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [feedback] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [feedback] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [feedback] SET  DISABLE_BROKER 
GO
ALTER DATABASE [feedback] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [feedback] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [feedback] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [feedback] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [feedback] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [feedback] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [feedback] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [feedback] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [feedback] SET  MULTI_USER 
GO
ALTER DATABASE [feedback] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [feedback] SET DB_CHAINING OFF 
GO
ALTER DATABASE [feedback] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [feedback] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [feedback] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [feedback] SET QUERY_STORE = OFF
GO
USE [feedback]
GO
/****** Object:  Table [dbo].[assign]    Script Date: 12/27/2020 2:49:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[assign](
	[id] [uniqueidentifier] NOT NULL,
	[to_employee] [uniqueidentifier] NOT NULL,
	[from_employee] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_assign] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[employee]    Script Date: 12/27/2020 2:49:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[employee](
	[id] [uniqueidentifier] NOT NULL,
	[name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_employee] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[review]    Script Date: 12/27/2020 2:49:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[review](
	[id] [uniqueidentifier] NOT NULL,
	[star] [int] NOT NULL,
	[from_employee] [uniqueidentifier] NOT NULL,
	[to_employee] [uniqueidentifier] NOT NULL,
	[created_at] [datetime] NOT NULL,
 CONSTRAINT [PK_review] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[assign]  WITH CHECK ADD  CONSTRAINT [FK_assign_employee] FOREIGN KEY([from_employee])
REFERENCES [dbo].[employee] ([id])
GO
ALTER TABLE [dbo].[assign] CHECK CONSTRAINT [FK_assign_employee]
GO
ALTER TABLE [dbo].[assign]  WITH CHECK ADD  CONSTRAINT [FK_assign_employee1] FOREIGN KEY([to_employee])
REFERENCES [dbo].[employee] ([id])
GO
ALTER TABLE [dbo].[assign] CHECK CONSTRAINT [FK_assign_employee1]
GO
ALTER TABLE [dbo].[review]  WITH CHECK ADD  CONSTRAINT [FK_review_employee] FOREIGN KEY([from_employee])
REFERENCES [dbo].[employee] ([id])
GO
ALTER TABLE [dbo].[review] CHECK CONSTRAINT [FK_review_employee]
GO
ALTER TABLE [dbo].[review]  WITH CHECK ADD  CONSTRAINT [FK_review_employee1] FOREIGN KEY([to_employee])
REFERENCES [dbo].[employee] ([id])
GO
ALTER TABLE [dbo].[review] CHECK CONSTRAINT [FK_review_employee1]
GO
USE [master]
GO
ALTER DATABASE [feedback] SET  READ_WRITE 
GO
